### ISSUE TITLE
Allow specifying repository by query string

### ISSUE THREAD

**Issue by tt** [csainty/Apphbify#2]
For applications not requiring any add-ons, it would be cool if you could just type in the GitHub project URL and run it on AppHarbor. This would allow you to easily try out simple projects (I wanted to try out @davidfowl's [HTML5 Bomberman](https://github.com/davidfowl/BombRMan), but didn't want to clone it locally).

**Comment by csainty** [comment]
Great idea!

I've got a refactor of the deployment process under way, breaking it into discreet command objects that you can chain together. That will make it really simple to do something like this without duplicating the process, just wire up a slightly different pipeline and off it will go.
