### ISSUE TITLE
How to disable email notification?

### ISSUE THREAD

**Issue by kki** [csainty/Apphbify#4]
I have enable email notification for my site several times for the same email address and now i have multiple notifications.

How to disable email notification for certain email?
Is there any ability to show list of subscribed email addresses and manage them?

**Comment by csainty** [comment]
There is currently no UI for this on appharbify.com

However, if you log in to your AppHarbor account and go to your site, under service hooks you will see all the urls that are used to trigger the emails.
Just delete any that are no longer needed.

https://appharbor.com/applications/{your project name}/servicehooks

**Comment by kki** [comment]
Thanks!
It works
