### ISSUE TITLE
WordPress On AppHarbor returns 404

### ISSUE THREAD

**Issue by dhrobbins** [csainty/Apphbify#6]
Deploy process completed successfully, but server comes up with 404 error.  Any ideas?

**Comment by csainty** [comment]
Did it eventually come good?
Fresh deploys can take some time to register with the AppHarbor load balancers.

**Comment by dhrobbins** [comment]
Looks like I was too impatient.  I had deployed and tried after a few minutes, but maybe still too soon.  WP is configuring now.  Wow, this could be really awesome.  Have you tried writing any plugins for WP with C#?
